package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Buildconfig'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Buildconfig")) {
    expectSteps {
        script {
            scriptContent = "echo a"
        }
    }
    steps {
        insert(1) {
            script {
                name = "New build step"
                scriptContent = "echo a"
            }
        }
        insert(2) {
            script {
                name = "New build step (1)"
                scriptContent = "echo a"
            }
        }
    }
}
