package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Secondaconfig'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Secondaconfig")) {
    expectSteps {
        script {
            name = "step1"
            scriptContent = "echo a"
        }
        script {
            name = "step2"
            scriptContent = "echo a"
        }
    }
    steps {
        insert(2) {
            script {
                scriptContent = "echo a"
            }
        }
        insert(3) {
            script {
                name = "my build steps _ with spaces !~@#${'$'}%&(*&_"
                scriptContent = "echo a"
            }
        }
    }
}
