package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.buildTypeCustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<CustomChart> {
            buildTypeCustomChart {
                id = "PROJECT_EXT_5"
                title = "Time per step"
                seriesTitle = "Serie"
                format = CustomChart.Format.DURATION
                defaultFilters = listOf(DefaultFilters.SHOW_FAILED)
                param("series", """
                    [
                    
                      {
                    
                        "type": "valueTypes",
                    
                        "pattern": "buildStageDuration:*"
                    
                         }
                    
                    ]
                """.trimIndent())
            }
        }
        feature1.apply {
            title = "Time per step"
            seriesTitle = "Serie"
            format = CustomChart.Format.DURATION
            defaultFilters = listOf(DefaultFilters.SHOW_FAILED)
            param("properties.axis.y.includeZero", "true")
            param("series", """
                [
                  {
                    "type": "valueTypes",
                    "pattern": "buildStageDuration:*"
                  }
                ]
            """.trimIndent())
            param("properties.axis.y.min", "")
            param("properties.axis.y.type", "default")
            param("properties.axis.y.max", "")
        }
        add {
            buildTypeCustomChart {
                id = "PROJECT_EXT_7"
                title = "my custom chart"
                seriesTitle = "Serie"
                format = CustomChart.Format.TEXT
                series = listOf(
                    Serie(title = "chubatova build step 1", key = SeriesKey.buildStepDuration("RUNNER_1")),
                    Serie(title = "chubatova build step2", key = SeriesKey.buildStepDuration("RUNNER_2"))
                )
            }
        }
    }
}
