package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Vampire_HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup'
in the project with id = 'Vampire', and delete the patch script.
*/
create(RelativeId("Vampire"), GitVcsRoot({
    id("Vampire_HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup")
    name = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
    url = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
    branch = "refs/heads/master"
}))

